// lex.yy.cpp generated by reflex 6.0.0 from LEXER.l

#define REFLEX_VERSION "6.0.0"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define REFLEX_OPTION_flex                true
#define REFLEX_OPTION_graphs_file         "lexer.gv"
#define REFLEX_OPTION_lex                 yylex
#define REFLEX_OPTION_lexer               yyFlexLexer
#define REFLEX_OPTION_outfile             "lex.yy.cpp"
#define REFLEX_OPTION_prefix              yy

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  FLEX-COMPATIBLE DEFINITIONS                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define INITIAL (0)
#define YY_NUM_RULES (14)

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  REGEX MATCHER                                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/matcher.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  FLEX-COMPATIBLE ABSTRACT LEXER CLASS                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/flexlexer.h>
typedef reflex::FlexLexer<reflex::Matcher> FlexLexer;

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS                                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

class yyFlexLexer : public FlexLexer {
 public:
  yyFlexLexer(
      // a persistent source of input, empty by default
      const reflex::Input& input = reflex::Input(),
      // optional output stream, NULL means std::cout by default
      std::ostream *os = NULL)
    :
      FlexLexer(input, os)
  {
  }
  // the flex lexer function defined by SECTION 2
  virtual int yylex(void);
  // lexer functions accepting new input to scan
  int yylex(const reflex::Input& input)
  {
    in(input);
    return yylex();
  }
  int yylex(const reflex::Input& input, std::ostream *os)
  {
    in(input);
    if (os)
      out(*os);
    return yylex();
  }
};

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 2: rules                                                          //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

int yyFlexLexer::yylex(void)
{
  static const char *REGEX_INITIAL = "(?m)((?:-)?(?:[0-9]+))|((?:[A-Z_a-z][0-9A-Z_a-z]*))|((?:\\Q-\\E))|((?:\\Q*\\E))|((?:\\Q/\\E))|((?:\\Q=\\E))|((?:[<>]=?|[!=]=))|((?:\\Q(\\E))|((?:\\Q)\\E))|((?:\\Q{\\E))|((?:\\Q}\\E))|((?:\\Q;\\E))|((?:\\Q&&\\E))|((?:\\Q||\\E))";
  static const reflex::Pattern PATTERN_INITIAL(REGEX_INITIAL);
  if (!has_matcher())
  {
    matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
    YY_USER_INIT
  }
#line 10 "LEXER.l"
COMMENT.*  /* ignore */
 [ \t] /*ignore*/

  while (true)
  {
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
              yyterminate();
            }
            else
            {
              output(matcher().input());
            }
            YY_BREAK
          case 1: // rule LEXER.l:10: {SIGN}?{NUM} :
            YY_USER_ACTION
#line 10 "LEXER.l"
return NUMBER;
            YY_BREAK
          case 2: // rule LEXER.l:11: {ID} :
            YY_USER_ACTION
#line 11 "LEXER.l"
return IDENTIFIER;

 "+"  return ADD;
            YY_BREAK
          case 3: // rule LEXER.l:14: "-" :
            YY_USER_ACTION
#line 14 "LEXER.l"
return SUBS;
            YY_BREAK
          case 4: // rule LEXER.l:15: "*" :
            YY_USER_ACTION
#line 15 "LEXER.l"
return MULT;
            YY_BREAK
          case 5: // rule LEXER.l:16: "/" :
            YY_USER_ACTION
#line 16 "LEXER.l"
return DIV;

            YY_BREAK
          case 6: // rule LEXER.l:18: "=" :
            YY_USER_ACTION
#line 18 "LEXER.l"
return ASSIGN;

            YY_BREAK
          case 7: // rule LEXER.l:20: ([<>]=?|[!=]=) :
            YY_USER_ACTION
#line 20 "LEXER.l"
return LOGICALOPERATOR;

            YY_BREAK
          case 8: // rule LEXER.l:22: "(" :
            YY_USER_ACTION
#line 22 "LEXER.l"
return OPAREN;
            YY_BREAK
          case 9: // rule LEXER.l:23: ")" :
            YY_USER_ACTION
#line 23 "LEXER.l"
return CPAREN;
            YY_BREAK
          case 10: // rule LEXER.l:24: "{" :
            YY_USER_ACTION
#line 24 "LEXER.l"
return OBRACKET;
            YY_BREAK
          case 11: // rule LEXER.l:25: "}" :
            YY_USER_ACTION
#line 25 "LEXER.l"
return CBRACKET;
            YY_BREAK
          case 12: // rule LEXER.l:26: ";" :
            YY_USER_ACTION
#line 26 "LEXER.l"
return POINTCOMMA;
            YY_BREAK
          case 13: // rule LEXER.l:27: "&&" :
            YY_USER_ACTION
#line 27 "LEXER.l"
return AND;
            YY_BREAK
          case 14: // rule LEXER.l:28: "||" :
            YY_USER_ACTION
#line 28 "LEXER.l"
return OR;

            YY_BREAK
        }
  }
}
